name: Fetch & Aggregate
on:
  schedule:
    - cron: "7 * * * *"      # hourly-ish (adjust as needed)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Install deps
        run: |
          npm ci || true   # tolerate no package.json

      - name: RSS ingest -> data/posts.json
        run: node ingest.mjs

      - name: X ingest -> data/x_raw.json
        # You already have x_ingest.py in your repo. Make sure it writes data/x_raw.json.
        run: |
          python3 -V
          python3 x_ingest.py || echo "Skipping X ingest (no creds or script)."

      - name: Aggregate X -> x_posts + heatmaps + summary
        run: |
          node x_aggregate.mjs || node aggregate.mjs || echo "No x_raw.json; wrote nothing."

      - name: Commit updated data files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git diff --cached --quiet || git commit -m "data: refresh $(date -u +%F_%T)Z"
          git push
