name: Fetch • Aggregate • X • Commit

on:
  schedule:
    - cron: '0 7 * * *'      # daily 07:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write            # allow the job to push data/*.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---- Node (RSS & insights) ----
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps
        run: npm ci || npm i

      - name: Ingest RSS
        run: node scripts/ingest.mjs

      - name: Aggregate RSS
        run: node scripts/aggregate.mjs

      - name: LLM Insights (OpenAI)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/llm_insights.mjs

      # ---- Python (X scraping) ----
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install snscrape
        run: |
          python -m pip install --upgrade pip
          python -m pip install snscrape

      - name: Ingest X posts (last 14 days)
        run: python scripts/x_ingest.py

      - name: Aggregate X heatmaps
        run: node scripts/x_aggregate.mjs

      # ---- Commit results ----
      - name: Commit data
        run: |
          git config user.name "gh-bot"
          git config user.email "bot@example.com"
          git add data/*.json
          git commit -m "data: refresh" || echo "no changes"
          git push
