name: Fetch & Aggregate Data

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */2 * * *'  # every 2 hours at :05

concurrency:
  group: fetch-data
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Ingest RSS
        run: npm run ingest:rss

      - name: Ingest X via Nitter
        run: npm run ingest:x

      - name: Aggregate X → heatmaps + posts
        run: npm run aggregate:x

      - name: Generate AI insights (optional)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        if: env.OPENAI_API_KEY != ''
        run: npm run insights

      - name: Commit /data changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "data: refresh"
            git push
          fi