name: Fetch & Build Data

on:
  schedule:
    - cron: "7 * * * *"   # hourly-ish
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---- Install dependencies if present (tolerate no package.json) ----
      - name: Install deps
        run: |
          npm ci || true

      # ---- RSS ingest -> /data/posts.json + /data/heatmap.json ----
      - name: RSS ingest
        run: node ingest.mjs

      # ---- X ingest (Nitter RSS) -> /data/x_raw.json ----
      - name: X ingest (Nitter RSS)
        run: |
          node scripts/x_ingest_nitter.mjs

      # ---- Aggregate X -> posts + heatmaps + summary ----
      - name: Aggregate X
        run: |
          node scripts/x_aggregate.mjs || node x_aggregate.mjs

      # ---- LLM insights (server-side only; requires OPENAI_API_KEY) ----
      - name: LLM insights -> data/insights.json
        if: ${{ github.event_name != 'pull_request' && secrets.OPENAI_API_KEY != '' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node llm_insights.mjs || echo "LLM insights skipped"

      # ---- Sanity check: guard against secret leaks in /data ----
      - name: Ensure secrets are not in outputs
        if: ${{ secrets.OPENAI_API_KEY != '' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -euo pipefail
          if grep -R --binary-files=without-match -n "$OPENAI_API_KEY" data/ >/dev/null 2>&1; then
            echo "❌ Secret appeared in /data output. Aborting."
            exit 1
          fi
          echo "✅ No secrets in /data artifacts."

      # ---- Commit data updates ----
      - name: Commit updated data files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git diff --cached --quiet || git commit -m "data: refresh $(date -u +%F_%T)Z"
          git push

      # ---- Kick off Pages deploy workflow (optional; pages.yml also runs on push) ----
      - name: Emit deploy hint
        run: echo "Data refreshed. Pages will deploy on push."