name: Fetch & Aggregate Data

on:
  workflow_dispatch:
  schedule:
    # run at :05 every 2 hours PT (adjust as you like)
    - cron: '5 */2 * * *'

concurrency:
  group: fetch-data
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Write .env if OPENAI key is present
        if: ${{ secrets.OPENAI_API_KEY != '' }}
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Fetch RSS posts
        run: node ingest.mjs

      - name: Aggregate X data (safe if x_raw.json missing)
        run: node aggregate.mjs

      - name: Generate LLM insights (optional)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node llm_insights.mjs

      - name: Commit refreshed data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "data: refresh"
          file_pattern: |
            data/*.json
